CREATE TABLE APP.STUDENT
(
	MATRIKEL	VARCHAR(9) NOT NULL,
	NAME 		VARCHAR(20),
	VORNAME		VARCHAR(20),
	ADRESSE		VARCHAR(200),
	SKUERZEL	VARCHAR(3) REFERENCES APP.STUDIENRICHTUNG(SKUERZEL),
	PRIMARY KEY	(MATRIKEL)
);

CREATE TABLE APP.PRAKTIKUMSTEILNAHME
(
	MATRIKEL	VARCHAR(9) NOT NULL REFERENCES APP.STUDENT(MATRIKEL),
	MKUERZEL	VARCHAR(5) NOT NULL REFERENCES APP.MODUL(MKUERZEL),
	SEMESTER	VARCHAR(7),
	TESTAT		BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (MATRIKEL, MKUERZEL, SEMESTER)
);
